import pantau
import time, sys, datetime, os, click
from datetime import datetime

from importlib import reload
pantau = reload(pantau)
time.sleep(26)
pantau = reload(pantau)
time.sleep(26)
pantau = reload(pantau)
time.sleep(26)
pantau = reload(pantau)
time.sleep(26)
pantau = reload(pantau)
time.sleep(26)
pantau = reload(pantau)
time.sleep(26)
pantau = reload(pantau)
time.sleep(26)
pantau = reload(pantau)
time.sleep(26)
pantau = reload(pantau)
time.sleep(26)
pantau = reload(pantau)
time.sleep(26)
pantau = reload(pantau)
time.sleep(26)
pantau = reload(pantau)
time.sleep(26)
pantau = reload(pantau)
time.sleep(26)
pantau = reload(pantau)
time.sleep(26)
pantau = reload(pantau)
time.sleep(26)
os.system ('python 1.py')
