import fapi
import time, sys, datetime, os, click
from datetime import datetime

from importlib import reload
fapi = reload(fapi)
time.sleep(26)
fapi = reload(fapi)
time.sleep(26)
fapi = reload(fapi)
time.sleep(26)
fapi = reload(fapi)
time.sleep(26)
fapi = reload(fapi)
time.sleep(26)
fapi = reload(fapi)
time.sleep(26)
fapi = reload(fapi)
time.sleep(26)
fapi = reload(fapi)
time.sleep(26)
fapi = reload(fapi)
time.sleep(26)
fapi = reload(fapi)
time.sleep(26)
fapi = reload(fapi)
time.sleep(26)
fapi = reload(fapi)
time.sleep(26)
fapi = reload(fapi)
time.sleep(26)
fapi = reload(fapi)
time.sleep(26)
fapi = reload(fapi)
time.sleep(26)
os.system ('python 2.py')
